### ISSUE TITLE
"Bridge Not Found" on WIndows 10 [0.0.6]

### ISSUE THREAD

**Issue by N-Upchurch** [hensm/fx_cast#117]
I'm receiving "Bridge not found" error on windows 10, with bridge installed.

**Comment by hensm** [comment]
Check the files/registry keys listed [here](https://hensm.github.io/fx_cast/#How_do_I_completely_remove_the_bridge?) and the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) log.

**Comment by N-Upchurch** [comment]
Keys are all there. ```HKCU\Software\Mozilla\NativeMessagingHosts\fx_cast_bridge``` exists, value is: C:\Program Files\fx_cast\fx_cast_bridge.json

Browser log: 
```
Unknown localization message quality_1080p (source) main.js:1
Unknown localization message quality_720p main.js:1
Unknown localization message quality_480p main.js:1
Unknown localization message quality_360p main.js:1
Unknown localization message quality_160p main.js:1
Unknown localization message quality_480p30 main.js:1
Unknown localization message quality_360p30 main.js:1
Unknown localization message quality_160p30 main.js:1
Unchecked lastError value: Error: Promised response from onMessage listener went out of scope 4 Message.js:9
g_CS[e] is null 5 background.js:1
[Exception... "Favicon at "https://hensm.github.io/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 227"  data: no] FaviconLoader.jsm:227:22
Promise rejected after context unloaded: Promised response from onMessage listener went out of scope
12 Message.js:9
Unchecked lastError value: Error: Promised response from onMessage listener went out of scope
```

**Comment by hensm** [comment]
Sorry for the delay. The key under HKCU (rather than HKLM) should only be set manually, or via one of the development scripts because it overrides the global key, so I'd double check that unless you've done one of those things.

In either case, if Firefox can't launch a native messaging host like fx_cast_bridge, the error will go to the browser console, so I'm not sure what's going on if there aren't any relevant logs. Perhaps something useful in the [add-on debugger console](https://extensionworkshop.com/documentation/develop/debugging/), but I doubt it.

**Comment by hensm** [comment]
Closing, feel free to re-open with logs if still an issue.
