### ISSUE TITLE
Casting of Google Play Music Skips to End of Album

### ISSUE THREAD

**Issue by BuzzfeedBlue** [hensm/fx_cast#148]
Using the 0.1 bridge and the 0.1.2 addon I am able to now cast apps like youtube and netflix 100% fine, but if I attempt to cast songs from the google play music site it will very quickly cycle down an entire album, then after, stream the last song succesfully, and then get soft locked on the google play music fireplace visualizer with a loading circle, and you are unable to use media controls. Will also continue to hold this state even if the tab is closed with "stop reciever playback on page unload" on.

Here are logs from browser, web, and addon debugging consoles respectively

https://pastebin.com/JDxYUE4Q
https://pastebin.com/82wwBUFc
https://pastebin.com/7p7ud0yY

**Comment by hensm** [comment]
Looks like GPM is shutting down soon and not accepting new signups, so I can't test this. Found a bug from those logs, but I don't think it's relevant here. It worked in the past (#47), but possibly something broke since then. Just out of interest, can you confirm whether this behaviour occurs when casting via Chrome?

> Will also continue to hold this state even if the tab is closed with "stop reciever playback on page unload" on.

The stop receiver playback option is only for HTML5 media, but you can stop an app if you hold alt or shift and click the "Cast" button in the popup.

**Comment by BuzzfeedBlue** [comment]
Chrome casts Google Play Music fine

**Comment by hensm** [comment]
Okay, managed to test it after all. I can only test with an uploaded music library, rather than the subscription catalogue, but it seems to work perfectly.

Clearly there's an issue, but I need to add better logging for this kind of thing.
