### ISSUE TITLE
Can't cast YouTube Music?

### ISSUE THREAD

**Issue by NullVoxPopuli** [hensm/fx_cast#185]
**OS version:** Windows 10
**Browser version:** Firefox Developer Edition: 90.0b9 
**Extension version:** 0.1.2
**Bridge version:**:  0.1.0

**Description**
![image](https://user-images.githubusercontent.com/199018/122581335-f0a9ec00-d024-11eb-9a3a-6172ccd9649f.png)

I cannot cast the tab

**Steps to reproduce**
1. install everything
2. visit YT Music
3. try casting

**Expected behaviour**
it works?.

**Logs**
n/a?

**Comment by NullVoxPopuli** [comment]
![image](https://user-images.githubusercontent.com/199018/122582291-f9e78880-d025-11eb-8f14-de3b45102628.png)

**Comment by NullVoxPopuli** [comment]
just found 
![image](https://user-images.githubusercontent.com/199018/122582306-ffdd6980-d025-11eb-9e6b-5f153589c93b.png)

**Comment by NullVoxPopuli** [comment]
so, I've enabled that now, but the cast dialog has not changed

**Comment by NullVoxPopuli** [comment]
Oh, I added this and the `Tab` option appeared:
![image](https://user-images.githubusercontent.com/199018/122582817-9578f900-d026-11eb-9111-9d9358f1ef70.png)

**Comment by NullVoxPopuli** [comment]
but the audio doesn't cast 🤔

**Comment by NullVoxPopuli** [comment]
maybe related to? https://github.com/hensm/fx_cast/issues/128

**Comment by hensm** [comment]
I haven't really tested it, but supposedly YouTube Music doesn't work right now. Otherwise, the tab casting has no audio due to API limitations.

YouTube Music compat issue:
hensm/fx_cast-compat#2

**Comment by Tschrock** [comment]
I've been able to successfully cast YouTube Music on Ubuntu after adding `https://music.youtube.com/*` to the User Agent Whitelist in the extension preferences. This is using the cast button that appears in the top right corner of the website.

**OS version:** Ubuntu 21.10
**Browser version:** Firefox 97.0 (Installed as a deb, not a snap)
**Extension version:** 0.1.2
**Bridge version:** 0.1.0

<details>

![ss1646519088-69429c](https://user-images.githubusercontent.com/2406499/156901763-90496f84-88ac-41f8-b6df-de7c99d7b618.png)
![ss1646519113-906d59](https://user-images.githubusercontent.com/2406499/156901766-f7e3cf78-ed77-4d65-8286-90a54e8c437c.png)

</details>

**Comment by TheW0LVERIN3** [comment]
On the latest fx_cast version(extension: 0.3.1 bridge: 0.3.0) youtube music doesn't work. I tested it using an android tv device with chromecast built-in running android 9 and the latest version of the chromecast built-in app(1.61.329909) as it's up to date on the play store. Interestingly though I did get the error: 
Unknown
Chromecast built-in | Unknown

**Comment by hensm** [comment]
Yep, broken for me too. Testing on a 3rd-gen chromecast, seems like the receiver app is crashing on startup for some reason. I'll try to take a better look at this tomorrow or next weekend. I'll open a new issue for it, since it's not related to this one.

**Comment by hensm** [comment]
@TheW0LVERIN3 So, it's a bit of a weird one. YouTube Music does work with fx_cast, but you have to be casting the song, rather than the video. If you try to cast the video, it'll try to use Chrome's tab mirroring functionality to cast the tab (with the audio).

<details>
<summary>Screenshot</summary>

![src](https://user-images.githubusercontent.com/6956633/218264482-23d2cbc3-8daa-43cb-b604-42a10254b830.png)

</details>

Since fx_cast doesn't handle that properly, it tries to launch the Chrome Mirroring app which then times out and returns to the home screen (or the indicator app launch appears/disappears on Google TV). It should probably handle this by using its own mirroring, but Firefox doesn't provide audio with the display stream so it would be kinda useless in this case anyway.

I assume the song mode requires a premium subscription since it wasn't there before I signed up for the trial.

If it still doesn't work for you, you may have a completely different issue specific to the Chromecast built-in app, which I'm not able to test. I'd try testing in Chrome to confirm it's related to fx_cast.

**Comment by TheW0LVERIN3** [comment]
@hensm So I guess I need youtube music premium to cast from firefox. That is unless firefox finally gets to supporting the audio tab sharing thing. Youtube music seems to have a bunch of these stupid bugs/bad design decisions. Thanks anyways for looking into it. 
Oh, and I tested with edge and it indeed does just cast the tab with audio instead of the chromecast "app". The stupid thing is that it works like it should with the youtube music android app.
