### ISSUE TITLE
another issue with maxstream

### ISSUE THREAD

**Issue by dylantrevor87** [hensm/fx_cast#214]
**OS version:** windows10
**Browser version:** firefox 100.0.2 (64-bit)
**Extension version:** 0.2.0
**Bridge version:** 0.2.0

**Description**
this is some sort of "followup" of bug #205 (fixed).
if I load a maxstream page and instead of playing or casting the video I click "download" button then the page won't load.
it stops on Cloudflare DDoS protection. If I disable fc_cast then the DDoS protection is successful and the page is loaded correctly.
You can test with the same link from bug 205:
https://maxstream.video/xqda7cebwflh/c3V4eWlYTmx3eXI3djZ5YTRQTGc3Zz09

**Comment by hensm** [comment]
I guess Cloudflare doesn't like the modified user agent string. Seems to work with the default one anyway, so I'll rework the whitelist feature to allow that at some point.

**Comment by hensm** [comment]
Kinda fixed in 539d2c6, also sort of wontfix.

It'll let you disable the user agent spoofing on that specific site, but since the site _doesn't_ actually seem to cast without a Chrome user agent string after all, you'll need a third party user agent changer that you can filter specifically to the watch page or toggle easily (since the match pattern filtering isn't flexible enough for that and not really something I want to implement).
