### ISSUE TITLE
No bridge found on Ubuntu with snap firefox

### ISSUE THREAD

**Issue by jlevon** [hensm/fx_cast#219]
**OS version:** Ubuntu 22.04 LTS x86_64
**Browser version:** Firefox 102.0
**Extension version:** 0.2.0
**Bridge version:** 0.2.0

Extension can't find the bridge. Browser console shows on e.g. youtube.com

```
ExtensionError: No such native application fx_cast_bridge
Error: fx_cast (Error): Bridge connection failed and backup not enabled.
```

**Comment by hensm** [comment]
The Firefox Snap can't connect to the bridge since it's sandboxed (#59), so you need to run the bridge as a daemon. There's some instructions for setting it up as systemd service in the [README](https://github.com/hensm/fx_cast#daemon-configuration=), but you can do it however you'd like. When you have it running, enable the daemon connection option under the bridge section on the options page.

**Comment by jlevon** [comment]
thanks, this worked.
https://github.com/hensm/fx_cast/pull/220
