### ISSUE TITLE
zoom (recording) support?

### ISSUE THREAD

**Issue by jlevon** [hensm/fx_cast#221]
version 0.2.0 - any chance of supporting Zoom recording casting?

**Comment by hensm** [comment]
I'm not too familiar with Zoom. Is this a Zoom feature or just screen mirroring?

If it's a Zoom feature, I can look into fixing any incompatibilities, but mirroring is much trickier to do properly because of API limitations and cross-platform differences. I think it's just straight up broken right now because of some canvas tainting issues in Firefox.

**Comment by jlevon** [comment]
I don't think it's screen mirroring. If it's useful I can probably record a small sample and share the link here.

**Comment by hensm** [comment]
That would be helpful, thanks.

**Comment by jlevon** [comment]
I tried but it's not easily doable to share due to policies on the pro account. The video itself is just an <video> with an mp4 file, but I'm not sure where on the page the cast stuff is loaded in Chrome, so maybe it *is* just screen mirroring. Presumably there's no way to just ask to cast a <video> element?

**Comment by hensm** [comment]
I think you lost the end of that comment.

I managed to find a picture of a shared recording page and it looks like a regular video player. There _is_ support for casting basic HTML5 media, though I'm guessing Zoom has some access restrictions that make that a non-starter. In any case, it's difficult to say without a live example.

**Comment by jlevon** [comment]
sorry, don't know where that went. Yes, the page appears to be just a <video> element with an mp4 link. I don't know what would or wouldn't trigger the ability to cast, I know basically nothing about what that looks like.

**Comment by jlevon** [comment]
TIL about the shift context menu! Unfortunately that doesn't work, it starts the chromecast connection but then nothing shows. Presumably cookie related like you mention, so I suppose there's nothing that can be done.

If I try "save video", it only saves a zero-byte HTML file too.

**Comment by hensm** [comment]
The only solution I can think of would be to capture a stream of the video and feed it into the screen mirroring connection. It's not really proper media casting since it's just a live stream of whatever the media element is doing, but probably better than nothing.

Currently re-working the mirroring stuff, so I might look into that. Chromecast receivers seem to have really bad WebRTC performance though, haven't fully investigated why.
