### ISSUE TITLE
Bridge installer may be installing the wrong version of the bridge

### ISSUE THREAD

**Issue by Rouble** [hensm/fx_cast#237]
**OS version:** Windows 10
**Browser version:** Firefox 104.0.2
**Extension version:** 0.3.1
**Bridge version:** 0.3.0

**Description**
The bridge installer for 0.3.0 is either installing the a wrong or mislabeled version of the bridge. The extension is detecting the newly installed 0.3.0 bridge as version 0.1.0 

**Steps to reproduce**
1. install extension version 0.3.1 from https://hensm.github.io/fx_cast/
2. install bridge version 0.3.0 from https://hensm.github.io/fx_cast/
3. receive error message that the "Bridge version is older than expected, try updating bridge to latest version" because it's being detected as version 0.1.0

**Troubleshooting steps taken**
removed extension via the Firefox extensions page and reinstalled extension from website
deleted the contents of C:\Program Files\fx_cast and reinstalled bridge from website

**Expected behaviour**
fx_cast_bridge-0.3.0-x64.exe should be installing bridge version 0.3.0

**Logs**
I get the following error in the browser console when closing the casting popup and when opening the extension settings but it doesn't seem related to the versioning issue

WebExtension context not found! [ExtensionParent.jsm:1255](resource://gre/modules/ExtensionParent.jsm)
    getContextById resource://gre/modules/ExtensionParent.jsm:1255
    recvRemoveListener resource://gre/modules/ExtensionParent.jsm:1234
    recvRemoveListener self-hosted:1151
    _recv resource://gre/modules/ConduitsChild.jsm:82
    receiveMessage resource://gre/modules/ConduitsParent.jsm:450

**Comment by hensm** [comment]
Have you ever installed v0.1.0 before?

Just deleting the install folder doesn't remove everything, since there are registry keys set for the native manifest path and uninstall info, though I'd expect it to just overwrite it when reinstalling.

One thing that could cause this is if you've ever installed a custom user-local version via the [`install-manifest`](https://github.com/hensm/fx_cast#instructions) script, since that would override the installer version.

Some more info that would be helpful:
* Values of these registry keys:
  * `Computer\HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\fx_cast_bridge`  
  * `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\fx_cast_bridge`
* Output of calling the bridge executable with the version CLI argument:
  `& 'C:\Program Files\fx_cast\fx_cast_bridge.exe' -v`
* Product version shown in the [control panel / settings app](https://user-images.githubusercontent.com/6956633/190924357-c1d7bbb9-a78d-4971-8277-de325b46aad9.png).

**Comment by Rouble** [comment]
It looks like `Computer\HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\fx_cast_bridge` was still pointing to where I'd built the bridge from source a while back, updating it to the correct location fixed the issue
