### ISSUE TITLE
Add the ability to simply cast the entire tab

### ISSUE THREAD

**Issue by ThatOhio** [hensm/fx_cast#254]
Often when I order food through doordash/ubereats/etc I like to cast the tab to my office tv so that my girlfriend and I can see when it is arriving. I wonder how complicated it would be to simply cast the content of the webpage and not only rely on finding video streams.

**Comment by hensm** [comment]
There is experimental screen mirroring support. You can enable it from the options page if you show advanced options.

I had to remove tab mirroring because of some weird issue on Chromecast devices with canvas streams, but you can still cast a specific window.

It's not good for video or anything where latency is important, but it should be fine for your use case.

**Comment by ThatOhio** [comment]
Oh wow yea this is perfect for what I need! Thanks so much!

**Comment by hensm** [comment]
@ghnp5 
You should be able to cast via the popup (opened from the toolbar button or menu item in the tools/context menu) by picking the screen option in the dropdown. That'll open a second window where you can use the Firefox screen sharing UI to pick which screen/window you want to stream.
