### ISSUE TITLE
Netflix blocks fx_cast

### ISSUE THREAD

**Issue by SupremeBananas** [hensm/fx_cast#297]
Windows 11
Firefox 125.0.3 (64-bits)
0.3.1
0.3.0

**Description**
If I go on Netflix with fx_cast enabled, Netflix tells me an update is needed (Screenshot)
![afbeelding](https://github.com/hensm/fx_cast/assets/53980859/355b788b-7396-4b24-9650-df7290561dbe)

For it to work again I must
1. disable the extension
2. refresh the page
3. log in
4. re-enable extension
5. start a series
6. refresh page again
7. then cast

Is this a known problem?

**Comment by hensm** [comment]
Probably the Chrome version in the user agent string is old enough that Netflix no longer support it. You can set a custom user agent in the whitelist settings.

**Comment by SupremeBananas** [comment]
> Probably the Chrome version in the user agent string is old enough that Netflix no longer support it. You can set a custom user agent in the whitelist settings.

I'm not too familiar with that, do I have to specify that below?
![afbeelding](https://github.com/hensm/fx_cast/assets/53980859/ec034418-3bc8-4ed7-bc60-5de08c1a0854)
Do I also need to disable the Whitelist, and can I just install the latest version of Chrome and copy the user agent from there? In my case: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by hensm** [comment]
Yep, that string should be fine, just put it in the user agent field and keep the whitelist enabled.

**Comment by SupremeBananas** [comment]
That did the trick! Thank you very much!

**Comment by bric3** [comment]
Could it be worth, having a notification to update this string, or have an auto-update of the version number ?

**Comment by hensm** [comment]
@bric3 

Yeah, I've considered it before. My issue with that is it'd mean the extension is "phoning home" periodically which I'm not a huge fan of. It's why the versioning scheme for the bridge is based on semver compatibility with the extension, so it can leverage the extension auto-update to notify of bridge updates.

It could be opt-in, but I'm not sure how much benefit that's going to provide since most users aren't going to enable it until _after_ they've gone through the process of troubleshooting it.

Maybe just regular patch version updates with new user agent strings between major/minor versions is the right way to handle this.

**Comment by bric3** [comment]
I see your point, maybe something simpler can be done : show a landing page when installing the extension, indicating it needs to report a different User-Agent string for castable websites. And this string is configurable in the extension config.
And it is advised to use the same as the latest version of Chrome.
