### ISSUE TITLE
support android 

### ISSUE THREAD

**Issue by ghost** [hensm/fx_cast#302]
**OS version:**
**Browser version:**
**Extension version:**
**Bridge version:**

**Description**
support android 

**Steps to reproduce**
1. List of steps
2. ...to reproduce the bug here

**Expected behaviour**
Describe the expected behaviour here.

**Logs**
Provide any applicable logs here. Info on where to find them is located [here](https://github.com/hensm/fx_cast/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by hensm** [comment]
This is probably quite a bit of work. I can think of a bunch of things that would need changes:

- Android app bridge. Running the Node.js bridge on Android inside of an wrapper App is probably possible (though not ideal), but would need a separate discovery implementation using NSD. Since native messaging isn't supported, it would need to use the WebSocket connection exclusively.
- The popup wouldn't work properly (if at all) and there are issues using the regular WebExtension popup since it's opened in response to a function call in the page script context and opening the popup programmatically requires a user action.
- Extension UI isn't responsive.
- Unsupported WebExtension APIs.
- Persistent background scripts aren't supported.

I don't use Android personally, so this isn't something I'm likely to work on any time soon (if ever), but I'd be happy to support anyone who's interested in working on this.
