### ISSUE TITLE
Youtube videos don't have cast option any more.

### ISSUE THREAD

**Issue by SubodhChettri** [hensm/fx_cast#85]
Upgraded to 0.0.4 and now youtube videos don't have cast option any more.

**Comment by bazingarj** [comment]
The Same issue is happening with me

**Comment by ThaDaVos** [comment]
Same here but I think it's related to: https://github.com/hensm/fx_cast/issues/12

**Comment by hensm** [comment]
@ThaDaVos It definitely still works in 0.0.3? I had trouble reproducing it last time I tested.

**Comment by ThaDaVos** [comment]
I haven't tested 0.0.3, only 0.0.4 and there it's broken, at least it doesn't show for me -> also when I whitelist youtube the layout changes, so maybe something more is happening

**Comment by hensm** [comment]
The layout changes because it's using an older Chrome UA because the new YouTube layout is broken with a Firefox UA due to the way it selectively loads Web Components polyfills for the older version of Polymer.

I haven't able to figure out the apparently arcane combination of polyfills to get it to work properly.

I'll do some more testing and see if I can reproduce the regression, but I never had much luck with YouTube before 0.0.4 either.

**Comment by hensm** [comment]
bdfd67b — Fixed. Just a dumb mistake.
log: https://gist.github.com/hensm/6a4419c53e6e0b2e92b5d9e2d559e4ad

**Comment by ThaDaVos** [comment]
New release? Or do I need to build it myself?

**Comment by hensm** [comment]
Leaving some time for localizations (#99) before a release, but you can build it yourself. Details in the README, let me know if you hit any issues.

**Comment by ThaDaVos** [comment]
I can do the NL ones (Dutch speaking :D)
